# Generated by Django 4.2.2 on 2023-06-17 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding', models.CharField(max_length=600)),
                ('Para1', models.CharField(max_length=1200)),
                ('para2', models.CharField(max_length=1200)),
                ('img', models.ImageField(upload_to='images')),
                ('tag', models.CharField(max_length=600)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='DRAFT', max_length=500)),
            ],
        ),
    ]
