# Generated by Django 4.2.2 on 2023-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Para1',
        ),
        migrations.AddField(
            model_name='news',
            name='rejectreason',
            field=models.CharField(default='none', editable=False, max_length=600),
        ),
        migrations.AlterField(
            model_name='news',
            name='headding',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='news',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='para2',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(default='DRAFT', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='news',
            name='para1',
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
