# Generated by Django 4.2.2 on 2023-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_remove_news_para1_news_rejectreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
