# Generated by Django 4.2.2 on 2023-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0003_news_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=600)),
                ('categoryvalue', models.CharField(blank=True, max_length=600)),
                ('section', models.CharField(blank=True, max_length=600)),
                ('sectionvalue', models.CharField(blank=True, max_length=600)),
            ],
        ),
    ]
