# Generated by Django 4.2.2 on 2023-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_choiselist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=600)),
                ('categoryvalue', models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiseListSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=600)),
                ('sectionvalue', models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='ChoiseList',
        ),
    ]
