# Generated by Django 4.2.2 on 2023-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_choiselistcategory_choiselistsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rebine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebine', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
