# Generated by Django 4.2.2 on 2023-06-22 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headding', models.CharField(blank=True, max_length=600)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('para1', models.CharField(blank=True, max_length=1200)),
                ('para2', models.CharField(blank=True, max_length=1200)),
                ('tag', models.CharField(blank=True, max_length=600)),
                ('img', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.CharField(max_length=350)),
                ('category', models.CharField(choices=[('India', 'India'), ('Sport', 'Sport'), ('Education', 'Education')], default='India', max_length=100)),
            ],
        ),
    ]
