# Generated by Django 4.2.2 on 2023-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=600)),
                ('categoryvalue', models.CharField(blank=True, max_length=600)),
                ('section', models.CharField(blank=True, max_length=600)),
                ('sectionvalue', models.CharField(blank=True, max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='category',
            field=models.CharField(choices=[('Main Page Hero Horizontal', 'Main Page Hero Horizontal'), ('Main Page Hero slide 1', 'Main Page Hero slide 1'), ('Main Page Hero slide 2', 'Main Page Hero slide 2'), ('Main Page Hadding News', 'Main Page Hadding News'), ('Main Page Sport News', 'Main Page Sport News'), ('Main Page Sport Polites', 'Main Page Sport Polites')], default='Main Page Hero Horizontal', max_length=100),
        ),
    ]
