# Generated by Django 4.2.2 on 2023-06-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_choiselist_alter_mainnews_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiseList',
        ),
    ]
