# Generated by Django 4.2.2 on 2023-07-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_choiselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='section',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='category',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
